import { StyleSheet, Dimensions } from 'react-native'
import type { Theme } from '../../theme'

const { width: SW } = Dimensions.get('window')

export const createRootStyles = () => StyleSheet.create({
  root: { flex: 1 },
  scroll: { flex: 1 },
  scrollContent: { paddingHorizontal: 16, paddingTop: 8 },
})

export const createHeaderStyles = (theme: Theme) => StyleSheet.create({
  container: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  greeting: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 14,
    color: theme.textPrimary,
    letterSpacing: 0.5,
    opacity: 1,
  },
  title: {
    fontFamily: 'CinzelDecorative_900Black',
    fontSize: 22,
    color: theme.textPrimary,
    letterSpacing: 2,
    textShadowColor: theme.shadowTextColor,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarLetter: {
    fontFamily: 'Cinzel_700Bold',
    fontSize: 18,
    color: theme.textOnAccent,
  },
})

export const createHeroStyles = (theme: Theme) => StyleSheet.create({
  card: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: `${theme.accentPrimary}40`,
    overflow: 'hidden',
    marginBottom: 28,
    height: 150,
  },
  glow: {
    position: 'absolute',
    inset: 0,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: `${theme.accentPrimary}26`,
  },
  content: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  plusCircle: { marginBottom: 4 },
  plusGradient: {
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: theme.shadowColor,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 12,
    elevation: 8,
  },
  label: {
    fontFamily: 'Cinzel_700Bold',
    fontSize: 16,
    color: theme.accentPrimary,
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  sub: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 12,
    color: theme.textSecondary,
  },
})

export const createSectionStyles = (theme: Theme) => StyleSheet.create({
  container: { marginBottom: 24 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 6,
  },
  dot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: theme.accentDark,
  },
  title: {
    fontFamily: 'Cinzel_700Bold',
    fontSize: 12,
    color: theme.textPrimary,
    letterSpacing: 2.5,
    textTransform: 'uppercase',
    flex: 1,
    opacity: 1,
  },
  count: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 12,
    color: theme.textTertiary,
  },
  cardRow: { gap: 12, paddingRight: 4 },
})

export const createActiveCardStyles = (theme: Theme) => StyleSheet.create({
  card: {
    width: 180,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: theme.borderSubtle,
    padding: 14,
    gap: 6,
    overflow: 'hidden',
    backgroundColor: theme.bgCard,
  },
  name: {
    fontFamily: 'Cinzel_700Bold',
    fontSize: 13,
    color: theme.textPrimary,
    letterSpacing: 0.5,
  },
  radius: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 11,
    color: theme.textTertiary,
  },
  progressBg: {
    height: 4,
    backgroundColor: `${theme.accentPrimary}1F`,
    borderRadius: 2,
    marginTop: 4,
  },
  progressFill: {
    height: 4,
    backgroundColor: theme.accentPrimary,
    borderRadius: 2,
  },
  progressLabel: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 10,
    color: theme.textTertiary,
  },
  gems: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: -6,
    marginTop: 2,
  },
  resumeBtn: { marginTop: 6 },
  resumeGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    borderRadius: 8,
    paddingVertical: 7,
  },
  resumeText: {
    fontFamily: 'Cinzel_700Bold',
    fontSize: 10,
    color: theme.textOnAccent,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
})

export const createFinishedRowStyles = (theme: Theme) => StyleSheet.create({
  row: {
    gap: 10,
    backgroundColor: theme.bgCard,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: theme.borderSubtle,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 10,
  },
  topRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  icon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: `${theme.textPrimary}26`,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconPerfect: {
    borderColor: `${theme.accentPrimary}66`,
    backgroundColor: `${theme.accentPrimary}14`,
  },
  info: { flex: 1 },
  name: {
    fontFamily: 'Cinzel_700Bold',
    fontSize: 13,
    color: theme.textPrimary,
    letterSpacing: 0.3,
  },
  meta: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 11,
    color: theme.textTertiary,
    marginTop: 2,
  },
  gems: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
})

export const createDeleteSheetStyles = (theme: Theme) => StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: theme.bgOverlay,
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: theme.bgCard,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderTopWidth: 1,
    borderColor: `${theme.colorError}33`,
    paddingHorizontal: 20,
  },
  handle: {
    alignSelf: 'center',
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: `${theme.textPrimary}33`,
    marginTop: 12,
    marginBottom: 20,
  },
  iconWrap: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: `${theme.colorError}1F`,
    borderWidth: 1,
    borderColor: `${theme.colorError}4D`,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: 16,
  },
  title: {
    fontFamily: 'Cinzel_700Bold',
    fontSize: 18,
    color: theme.textPrimary,
    letterSpacing: 1,
    textAlign: 'center',
    marginBottom: 8,
  },
  gameName: {
    fontFamily: 'CinzelDecorative_900Black',
    fontSize: 14,
    color: theme.accentPrimary,
    textAlign: 'center',
    marginBottom: 8,
  },
  sub: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    color: theme.textSecondary,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 28,
  },
  footer: {
    flexDirection: 'row',
    gap: 10,
  },
  cancelBtn: {
    flex: 1,
    height: 52,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: `${theme.textPrimary}33`,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelText: {
    fontFamily: 'Cinzel_700Bold',
    fontSize: 13,
    color: theme.textSecondary,
    letterSpacing: 1,
  },
  deleteBtn: {
    flex: 1,
    height: 52,
    borderRadius: 12,
    backgroundColor: `${theme.colorError}26`,
    borderWidth: 1,
    borderColor: `${theme.colorError}66`,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  deleteText: {
    fontFamily: 'Cinzel_700Bold',
    fontSize: 13,
    color: theme.colorError,
    letterSpacing: 1,
  },
})

export const createWizardStyles = (theme: Theme) => StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: theme.bgOverlay,
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: theme.bgCard,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderTopWidth: 1,
    borderColor: `${theme.accentPrimary}26`,
    paddingHorizontal: 20,
  },
  handle: {
    alignSelf: 'center',
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: `${theme.textPrimary}33`,
    marginTop: 12,
    marginBottom: 20,
  },
  stepRow: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 24,
    justifyContent: 'center',
  },
  stepDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: `${theme.textPrimary}26`,
  },
  stepDotActive: {
    backgroundColor: theme.accentPrimary,
    width: 20,
  },
  stepContent: { gap: 10, minHeight: 220 },
  stepTitle: {
    fontFamily: 'Cinzel_700Bold',
    fontSize: 18,
    color: theme.textPrimary,
    letterSpacing: 1,
  },
  stepSub: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    color: theme.textSecondary,
    marginBottom: 8,
  },
  inputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.bgInput,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.borderPrimary,
    height: 54,
    paddingHorizontal: 16,
  },
  input: {
    flex: 1,
    fontFamily: 'Nunito_400Regular',
    fontSize: 15,
    color: theme.textPrimary,
  },
  radiusGrid: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  radiusBtn: {
    flex: 1,
    minWidth: (SW - 72) / 2,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: `${theme.textPrimary}26`,
    height: 72,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    overflow: 'hidden',
  },
  radiusBtnActive: { borderColor: theme.accentPrimary },
  radiusLabel: {
    fontFamily: 'Cinzel_700Bold',
    fontSize: 13,
    color: theme.textSecondary,
    letterSpacing: 1,
  },
  radiusLabelActive: { color: theme.textOnAccent },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 24,
    gap: 12,
  },
  backBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 4,
  },
  backBtnText: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 14,
    color: theme.textSecondary,
  },
  nextBtnWrap: { flex: 1 },
  nextBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 12,
    height: 52,
    shadowColor: theme.shadowColor,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 6,
  },
  nextBtnText: {
    fontFamily: 'Cinzel_700Bold',
    fontSize: 14,
    color: theme.textOnAccent,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
})
